### ISSUE TITLE
Normal + Wildcard domains cause errors, such as "example.dev.txt: No such file or directory"

### ISSUE THREAD

**Issue by TheFirsh** [sineverba/cfhookbash#72] opened 2020-12-28 17:44 UTC
- Pretty fresh Ubuntu Server 20
- I manually remove these TXT from Cloudflare after a failure
- When domains are (with my domain ofc): `example.dev *.example.dev` or `example.dev *.example.dev > star_example_dev` the problem occurs. Looks like there is no differentation between the wildcard and the regular, and it ends up wanting to create multiple identical TXT records (same value).
- These all work: `*.example.dev > star_example_dev` or `example.dev`
- Tried running as root, no difference
- jq version 1.6
- The config.sh includes 1 entry with api_token (with DNS:Edit permission for the domain) and zones filled.

Command I run:

`./dehydrated --cron --accept-terms --challenge dns-01 --hook cfhookbash/hook.sh --ca https://acme-staging-v02.api.letsencrypt.org/directory --force-validation --force`

The DELETE method **is** supported with API Tokens, I just tested them with Postman and using what you use in `clean_challenge` I can delete a record just fine. What your script does when this error is produced, is to make a call that ends with `.../dns_records/` and no ID after that.

I try to catch this file while it exists:
`{"result":null,"success":false,"errors":[{"code":81057,"message":"The record already exists."}],"messages":[]}`

As you can see your line 91 ` printf "id: %s\n" "${id}"` produces just "id:" so the **id** variable is not available for the cleanup.

```
 + Responding to challenge for example.dev authorization...
 + Challenge is valid!
 + Responding to challenge for example.dev authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
id: d6d1140c634e38eb938e52c3d9ad1b1c
{"result":{"id":"d6d1140c634e38eb938e52c3d9ad1b1c"},"success":true,"errors":[],"messages":[]}cat: /home/firsh/acme/cfhookbash/example.dev.txt: No such file or directory
id:
{"success":false,"errors":[{"code":10000,"message":"DELETE method with API Tokens is not supported by this API"}]}
rm: cannot remove '/home/firsh/acme/cfhookbash/example.dev.txt': No such file or directory
ERROR: clean_challenge hook returned with non-zero exit code
```

**Comment by sineverba** [comment] 2020-12-28 19:48
So, if I understood correctly, if you try to authenticate **only** `*.example.dev` OR `example.dev` does it work?

**Comment by TheFirsh** [comment] 2020-12-28 19:53
Yes, standalone they work. But it's from https://github.com/dehydrated-io/dehydrated/blob/master/docs/domains_txt.md and it's valid to specify both at the same time. Result is a single cert with both top level and * subdomains in it (SAN mode = Subject Alternative Name). The acme.sh does this no problem.

**Comment by gruentee** [comment] 2021-01-09 23:54
I can confirm the issue.

**Comment by sineverba** [comment] 2021-01-10 08:41
Can you try for your wildcard domains to place this in `config.sh` ?

```shell
case ${1} in
    "example.com")

[...]
```
E.g. the domain name without prefix?

And check if produced certificate is really valid?

**Comment by BMicraft** [comment] 2021-02-01 20:59
> Can you try for your wildcard domains to place this in `config.sh` ?
> 
> ```shell
> case ${1} in
>     "example.com")
> 
> [...]
> ```
> 
> E.g. the domain name without prefix?
> 
> And check if produced certificate is really valid? They would be placed in "star.example.com" (without underscore but with dots).

Not op, but I did it without `www.` in config and it did not work.

```
# INFO: Using main config file /etc/dehydrated/config
+ Fetching account URL...
Processing example.net with alternative names: *.example.net
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jan 31 18:10:54 2021 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for example.net
 + Handling authorization for example.net
 + 2 pending challenge(s)
 + Deploying challenge tokens...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   677    0   526  100   151    516    148  0:00:01  0:00:01 --:--:--   665
+++ Wait for 10 seconds. +++
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   677    0   526  100   151    498    142  0:00:01  0:00:01 --:--:--   641
+++ Wait for 10 seconds. +++
 + Responding to challenge for example.net authorization...
 + Cleaning challenge tokens...
id: some_id_b3fd
{"result":{"id":"some_id_b3fd"},"success":true,"errors":[],"messages":[]}cat: /root/cfhookbash/example.net.txt: No such file or directory
id: 
{"success":false,"errors":[{"code":10000,"message":"DELETE method with API Tokens is not supported by this API"}]}
rm: cannot remove '/root/cfhookbash/example.net.txt': No such file or directory
ERROR: clean_challenge hook returned with non-zero exit code
```

**Comment by BMicraft** [comment] 2021-02-01 21:04
I found the problem, it seems you need to specify a different case for `*.example.net` because `cfhookbash` will not just use `example.net` for that.

**Comment by BMicraft** [comment] 2021-02-01 21:10
Okay I don't know what just happened, but It seemed to work _once_.
Maybe there is a race condition somewhere?

**Comment by sineverba** [comment] 2021-02-01 21:15
Got a similar issue at the start of this year. Second time, it worked.
By the way, I use the script **only with a single domain for line**, as stated on README.
I don't know if this could be the cause of the issues... I.e. I have a simply necessity... Get certificate only for two simply domains (or better, for a domain and 2 subdomains... www.example.com and test.exmaple.com).

**Comment by BMicraft** [comment] 2021-02-02 04:14
I've been digging into this, but one thing I just can't seem to get working is this:

```
curl -X DELETE https://api.cloudflare.com/client/v4/zones/MY_ZONE/dns_records/MY_RECORD -H 'Authorization: Bearer something-something' -H 'Content-Type: application/json'
```

That command will _always_ report an error for use of api tokens aka non-legacy auth
```
{"success":false,"errors":[{"code":10000,"message":"DELETE method with API Tokens is not supported by this API"}]}
```

Has this ever worked - and if so, how?

**Comment by fallingcats** [comment] 2021-02-02 06:40
I hope this could be merged as it has fixed the problem for me. Please test so it does not cause any regressions :)

I am also working on another PR to support the `HOOK_CHAIN="yes"` option of `dehydrated` which will make deploying faster by only waiting once for dns propagation after deploying all challenge tokens at once.

**Closed** 2021-02-02 07:49 UTC
